server:
  port: 9091

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservices
    username: postgres
    password: ${db_pass}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  application:                      # this property is used to give our application one name so now in eureka
    name: Rating-Service            # server our application will be visible with this name.

  config:                           # this propes is used to connect to the config-server
#    import: optional:configserver:http://localhost:9094
    import: optional:configserver:http://Config-Server

# Below props are configured in config-files which can be fetched using config-server.
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:                                    # this property will tell our microservice ki kis server ke
#      defaultZone: http://localhost:8761/eureka     # paas jake register hona hai.

